### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by llPushkarSinghll** [Mcbeany/BetterMinion#4]
1. Incomplete command = internal server error
2. idk why but wood minion not working in my video
https://youtu.be/5BETMmV5SsA
I cut the scene but wood minion was not working

**Comment by Mcbeany** [comment]
> 2. idk why but wood minion not working in my video

it works for me

**Comment by Mcbeany** [comment]
i saw that video, you have to place grass first lol

**Comment by llPushkarSinghll** [comment]
> i saw that video, you have to place grass first lol

Lol

**Comment by llPushkarSinghll** [comment]
> which command?

Incomplete command

**Comment by Mcbeany** [comment]
wdym?
